import { Inter } from "next/font/google";
import "./globals.css";
import { MoviesProvider } from "../context/movies.jsx";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/water.css@2/out/water.css"
        />
      </head>
      <MoviesProvider>
        <body className={inter.className}>{children}</body>
      </MoviesProvider>
    </html>
  );
}
